name: Test WARP

on:
  workflow_dispatch:

jobs:
  warp:
    runs-on: ubuntu-latest

    steps:
      - name: Before WARP
        run: |
          echo "Before:"
          curl -4s https://api.ipify.org
          echo

      - name: Install WARP
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg \
            | sudo gpg --yes --dearmor \
            -o /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg

          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(. /etc/os-release && echo "$VERSION_CODENAME") main" \
            | sudo tee /etc/apt/sources.list.d/cloudflare-client.list

          sudo apt-get update
          sudo apt-get install -y cloudflare-warp

      - name: Start WARP
        run: |
          sudo warp-cli registration new
          sudo warp-cli connect

          sleep 5

          sudo warp-cli status

      - name: Test IP
        run: |
          echo "After:"
          curl -4s https://api.ipify.org
          echo

          echo "Cloudflare:"
          curl -s https://www.cloudflare.com/cdn-cgi/trace | grep '^warp='
